# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
 identifier = "about"
 name = "About"
 pageRef = "/about"
 weight = 100

[[main]]
 identifier = "posts"
 name = "Posts"
 pageref = "/posts"
 weight = 200

[[main]]
 identifier = "projects"
 name = "Projects"
 pageRef = "/projects"
 weight = 300

[[main]]
 identifier = "career"
 name = "Career"
 weight = 400

[[main]]
 name = "Experience"
 parent = "career"
 pageRef = "experience"
 weight = 100

[[main]]
 name = "Skills"
 parent = "career"
 pageRef = "skills"
 weight = 200

[[main]]
 name = "Education"
 parent = "career"
 pageRef = "education"
 weight = 300

[[main]]
 name = "Resume"
 pageRef = "resume"
 weight = 500

[[main]]
 name = "Bionic Frog"
 parent = "projects"
 pageRef = "frog"
 weight = -100
 
[[main]]
 name = "Î¼CHIMERA"
 parent = "projects"
 pageRef = "uCHIMERA"
 weight = -200
 
[[main]]
 name = "TachyðŸª³Astroach: MoonLine"
 parent = "projects"
 pageRef = "posts"
 weight = -300 

[[subnavigation]]
 identifier = "journal"
 name = "â—¹"
 url = "https://journal.purticra.icu"
 weight = 20

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
  # name = ""
  # pageRef = "tags"
  # weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20